# Configuration file for Prettier
# Used before every commit to format the code-style

printWidth: 160
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
trailingComma: es5
bracketSpacing: true
arrowParens: avoid
endOfLine: lf
htmlWhitespaceSensitivity: ignore
