name: Build
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ vars.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build
        id: build
        run: npm run build

      - name: 'Upload Artifact'
        if: ${{ steps.build.outputs.exit-code == 0 }}
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: lib
          retention-days: 5