name: Check linter
on: [pull_request]

jobs:
  check-linter:
    name: Check linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            src/**/*.ts

      - name: Set up Node
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npm ci

      - name: Check ESLint
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npm run lint:ci -- ${{ steps.changed-files.outputs.all_changed_files }}
