name: Check prettier
on: [pull_request]

jobs:
  check-prettier:
    name: Check prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            *.md
            src/**/*.ts

      - name: Set up Node
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npm ci

      - name: Check prettier
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npm run prettier:ci -- ${{ steps.changed-files.outputs.all_changed_files }}
