name: Check prettier
on: [pull_request]

jobs:
  check-prettier:
    name: Check prettier
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Node.js dependencies
        run: npm ci

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            *.md
            src/**/*.ts

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Lint
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npm run prettier:ci -- ${{ steps.changed-files.outputs.all_changed_files }}
